### ISSUE TITLE
Replace JetBrains annotations with Spring ones

### ISSUE THREAD

**Issue by ledsoft** [kbss-cvut/termit#296]
A mix of JetBrains (`org.jetbrains.annotations`, e.g. `@NotNull`) and Spring (`org.springframework.lang`, e.g., `@NonNull`) is used within TermIt. We need to unify these to the Spring-based ones.

**Comment by lukaskabc** [comment]
I am looking at the options, and I think we should consider JSpecify annotations.

`jakarta.validation.constraints.NotNull` is used for bean validation. This should stay unchanged for runtime bean validation.

There are also [`Nonnull`](https://jakarta.ee/specifications/annotations/2.1/annotations-spec-2.1.html#jakarta-annotation-nonnull) and [`Nullable`](https://jakarta.ee/specifications/annotations/2.1/annotations-spec-2.1.html#jakarta-annotation-nullable) from `jakarta.annotation` that are intended for static analysis.

Spring's [@NonNull](https://github.com/spring-projects/spring-framework/blob/598580020e3b5f72ea03990882dac37d8c0aa128/spring-core/src/main/java/org/springframework/lang/NonNull.java#L52) currently uses `Nonnull` from the old javax.
However, they seem to be planning a [migration to JSpecify](https://github.com/spring-projects/spring-framework/issues/28797).

I suggest using JSpecify, too.

https://jspecify.dev/

@ledsoft 

# IDE configuration
Once this is resolved, it is possible to change the Intellij idea configuration to use desired annotations for code generation instead of the ones from Jetbrains. And it should be mentioned in [implementation docs](https://github.com/kbss-cvut/termit/blob/master/doc/implementation.md).

https://www.jetbrains.com/help/idea/annotating-source-code.html#nullability-annotations

**Comment by ledsoft** [comment]
I would actually prefer the standard Jakarta `Nonnull`. It seems to work with IDEA out of the box and we already depend on Jakarta annotations.
Let's put this one on hold, I will ask a friend at Payara what they use.

**Comment by ledsoft** [comment]
Ok, I suggest going with the standard Jakarta annotations. It requires no additional dependencies and works fine with IDEs without any extra configuration.
